# Generated by Django 5.2.15 on 2026-06-16 03:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, help_text='资料所有者 ID', max_length=64)),
                ('display_title', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('active', '可用'), ('archived', '已归档')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '资料',
                'verbose_name_plural': '资料',
                'db_table': 'knowledge_source',
            },
        ),
        migrations.CreateModel(
            name='SourceVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('content_sha256', models.CharField(db_index=True, max_length=64)),
                ('object_key', models.CharField(help_text='原始文件对象存储键', max_length=512)),
                ('media_type', models.CharField(default='application/pdf', max_length=128)),
                ('byte_size', models.BigIntegerField()),
                ('original_filename', models.CharField(blank=True, default='', max_length=512)),
                ('processing_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16)),
                ('artifact_ref', models.CharField(blank=True, default='', help_text='ParsedBundle JSON 对象存储键', max_length=512)),
                ('parser_name', models.CharField(blank=True, default='', max_length=64)),
                ('parser_version', models.CharField(blank=True, default='', max_length=32)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='knowledge.sourceversion')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.source')),
            ],
            options={
                'verbose_name': '资料版本',
                'verbose_name_plural': '资料版本',
                'db_table': 'knowledge_source_version',
            },
        ),
        migrations.AddField(
            model_name='source',
            name='latest_version',
            field=models.ForeignKey(blank=True, help_text='最新资料版本', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.sourceversion'),
        ),
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=16)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('parser_name', models.CharField(default='pymupdf', max_length=64)),
                ('parser_version', models.CharField(default='1.23.0', max_length=32)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_runs', to='knowledge.sourceversion')),
            ],
            options={
                'verbose_name': '处理运行',
                'verbose_name_plural': '处理运行',
                'db_table': 'knowledge_processing_run',
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=64)),
                ('object_key', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('pending', '待上传'), ('uploading', '上传中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16)),
                ('expected_byte_size', models.BigIntegerField(blank=True, null=True)),
                ('content_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('media_type', models.CharField(default='application/pdf', max_length=128)),
                ('original_filename', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to='knowledge.sourceversion')),
            ],
            options={
                'verbose_name': '上传会话',
                'verbose_name_plural': '上传会话',
                'db_table': 'knowledge_upload_session',
            },
        ),
        migrations.AddIndex(
            model_name='sourceversion',
            index=models.Index(fields=['content_sha256'], name='knowledge_s_content_1f2302_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceversion',
            index=models.Index(fields=['processing_status'], name='knowledge_s_process_25d37e_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourceversion',
            constraint=models.UniqueConstraint(fields=('source', 'version_number'), name='knowledge_srcver_version_unique'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['owner_id', 'created_at'], name='knowledge_s_owner_i_e69aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='processingrun',
            index=models.Index(fields=['source_version', 'status'], name='knowledge_p_source__823ce4_idx'),
        ),
    ]
