# Generated by Django 5.2.15 on 2026-06-25 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_session_id', models.CharField(db_index=True, help_text='CourseCreationSession.id（UUID 字符串）', max_length=64)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('source_version', models.ForeignKey(help_text='关联的资料版本', on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='knowledge.sourceversion')),
            ],
            options={
                'verbose_name': '课程资料关联',
                'verbose_name_plural': '课程资料关联',
                'db_table': 'knowledge_course_source',
                'constraints': [models.UniqueConstraint(fields=('course_session_id', 'source_version'), name='knowledge_coursesource_uc')],
            },
        ),
    ]
