# Generated by Django 6.0.6 on 2026-06-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_coursesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='tags',
            field=models.JSONField(default=list, help_text="自由标签列表，如 ['408统考', '重点']"),
        ),
    ]
