# Generated by Django 6.0.6 on 2026-06-27 02:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_add_source_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.libraryfolder')),
            ],
            options={
                'verbose_name': '资料文件夹',
                'verbose_name_plural': '资料文件夹',
                'db_table': 'knowledge_folder',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='source',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='所属文件夹', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='knowledge.libraryfolder'),
        ),
        migrations.AddIndex(
            model_name='libraryfolder',
            index=models.Index(fields=['owner_id'], name='knowledge_f_owner_i_4f7030_idx'),
        ),
    ]
