# Generated by Django 6.0.6 on 2026-06-24 01:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_session_id', models.UUIDField(db_index=True, help_text='关联的 CourseCreationSession ID。等 courses 模块补充 Course model 后迁移为 FK。')),
                ('active_revision_id', models.UUIDField(blank=True, help_text='当前生效的 LearningPlanRevision ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '学习计划',
                'verbose_name_plural': '学习计划',
                'db_table': 'learning_plan',
            },
        ),
        migrations.CreateModel(
            name='LearningPlanRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_revision_id', models.UUIDField(blank=True, help_text='上一版本修订 ID，首次创建为 None', null=True)),
                ('profile_revision_id', models.CharField(blank=True, default='', help_text='课程画像修订 ID', max_length=128)),
                ('knowledge_scope_revision_id', models.CharField(blank=True, default='', help_text='知识作用域修订 ID', max_length=128)),
                ('plan_snapshot_json', models.JSONField(default=dict, help_text='PlannerAgent 输出的完整计划快照（阶段/单元/任务模板）')),
                ('feasibility_status', models.CharField(choices=[('feasible', '可行'), ('constrained', '受限'), ('infeasible', '不可行')], default='feasible', max_length=16)),
                ('validation_result_json', models.JSONField(blank=True, help_text='校验结果：前置依赖、时长预算、覆盖率等', null=True)),
                ('status', models.CharField(choices=[('generating', '生成中'), ('draft', '草稿'), ('ready_to_start', '待启动'), ('active', '生效中'), ('needs_replan', '需重规划'), ('superseded', '已替代'), ('abandoned', '已放弃')], default='draft', max_length=16)),
                ('lock_version', models.IntegerField(default=0, help_text='乐观锁版本号，每次编辑递增')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='learning.learningplan')),
            ],
            options={
                'verbose_name': '计划修订',
                'verbose_name_plural': '计划修订',
                'db_table': 'learning_plan_revision',
            },
        ),
        migrations.CreateModel(
            name='LearningPlanPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(help_text='阶段序号，0-based')),
                ('title', models.CharField(max_length=128)),
                ('objective', models.TextField(blank=True, default='')),
                ('estimated_minutes', models.IntegerField(default=0)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='learning.learningplanrevision')),
            ],
            options={
                'verbose_name': '学习阶段',
                'verbose_name_plural': '学习阶段',
                'db_table': 'learning_plan_phase',
                'ordering': ['revision', 'position'],
            },
        ),
        migrations.CreateModel(
            name='LearningPlanUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_id', models.UUIDField(blank=True, help_text='关联 knowledge topic ID', null=True)),
                ('position', models.IntegerField()),
                ('target_depth', models.CharField(choices=[('basic', '基础'), ('reinforce', '强化'), ('review', '复习'), ('skip', '跳过')], default='basic', max_length=16)),
                ('estimated_minutes', models.IntegerField(default=0)),
                ('prerequisite_unit_ids', models.JSONField(default=list, help_text='前置学习单元 ID 列表')),
                ('priority', models.IntegerField(default=0)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='learning.learningplanphase')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='learning.learningplanrevision')),
            ],
            options={
                'verbose_name': '学习单元',
                'verbose_name_plural': '学习单元',
                'db_table': 'learning_plan_unit',
                'ordering': ['revision', 'phase', 'position'],
            },
        ),
        migrations.CreateModel(
            name='LearningPlanTaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('lecture', '讲解'), ('exercise', '练习'), ('project', '项目'), ('review', '复习')], max_length=16)),
                ('delivery_mode', models.CharField(choices=[('text', '文本'), ('video', '视频'), ('interactive', '交互式')], default='text', max_length=16)),
                ('estimated_minutes', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='learning.learningplanrevision')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='learning.learningplanunit')),
            ],
            options={
                'verbose_name': '任务模板',
                'verbose_name_plural': '任务模板',
                'db_table': 'learning_plan_task_template',
                'ordering': ['unit', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='learningplanrevision',
            index=models.Index(fields=['learning_plan', '-created_at'], name='learning_pl_learnin_15ad80_idx'),
        ),
        migrations.AddIndex(
            model_name='learningplanrevision',
            index=models.Index(fields=['status'], name='learning_pl_status_f3590a_idx'),
        ),
    ]
