# Generated by Django 6.0.6 on 2026-06-26 01:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='任务标题', max_length=256)),
                ('task_type', models.CharField(choices=[('lecture', '讲解'), ('exercise', '练习'), ('project', '项目'), ('review', '复习')], max_length=16)),
                ('status', models.CharField(choices=[('pending', '待完成'), ('in_progress', '进行中'), ('completed', '已完成'), ('skipped', '已跳过')], default='pending', max_length=16)),
                ('position', models.IntegerField(default=0)),
                ('estimated_minutes', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='建议完成日期', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.learningplanrevision')),
                ('template', models.ForeignKey(blank=True, help_text='来源模板', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='learning.learningplantasktemplate')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.learningplanunit')),
            ],
            options={
                'verbose_name': '学习任务',
                'verbose_name_plural': '学习任务',
                'db_table': 'learning_task',
                'ordering': ['revision', 'due_date', 'position'],
                'indexes': [models.Index(fields=['revision', 'status'], name='learning_ta_revisio_930fb5_idx')],
            },
        ),
    ]
