# Generated by Django 6.0.6 on 2026-06-27 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_add_learning_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningHistoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.CharField(db_index=True, help_text='关联课程 ID', max_length=128)),
                ('event_type', models.CharField(choices=[('task_completed', '完成学习任务'), ('task_started', '开始学习任务'), ('check_passed', '通过检查点'), ('check_failed', '检查未通过'), ('stage_changed', '阶段切换'), ('plan_adjusted', '方案调整'), ('source_added', '新增课程资料'), ('source_updated', '资料版本更新'), ('quiz_attempted', '尝试测验'), ('skill_mastered', '技能掌握'), ('course_started', '开始课程'), ('course_paused', '暂停课程')], max_length=20)),
                ('title', models.CharField(max_length=512)),
                ('detail', models.TextField(blank=True, default='')),
                ('result', models.CharField(blank=True, default='', max_length=128)),
                ('task_id', models.CharField(blank=True, default='', max_length=128)),
                ('phase_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': '学习记录',
                'verbose_name_plural': '学习记录',
                'db_table': 'learning_history_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course_id', '-created_at'], name='learning_hi_course__be5dc2_idx')],
            },
        ),
    ]
