# Generated by Django 6.0.6 on 2026-06-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_add_history_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplantasktemplate',
            name='content_json',
            field=models.JSONField(default=dict, help_text='任务内容块数组 {content_blocks: [...], sources: [...]}'),
        ),
    ]
