# Generated by Django 6.0.6 on 2026-06-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_learningplantasktemplate_content_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningplantasktemplate',
            name='content_json',
        ),
        migrations.AddField(
            model_name='learningtask',
            name='content_json',
            field=models.JSONField(default=dict, help_text='任务内容 {content_blocks: [...], source_evidence_ids: [...]}'),
        ),
    ]
