# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_remove_learningplantasktemplate_content_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningplanunit",
            name="title",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="learningplantasktemplate",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="learningplantasktemplate",
            name="knowledge_point",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="learningplantasktemplate",
            name="title",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
