# Generated by Codex on 2026-07-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0006_add_unit_and_task_titles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningplantasktemplate",
            options={
                "ordering": ["unit", "position", "id"],
                "verbose_name": "任务模板",
                "verbose_name_plural": "任务模板",
            },
        ),
    ]
