# Generated by Django 5.2.15 on 2026-07-10 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owner(apps, schema_editor):
    User = apps.get_model("users", "User")
    user, _ = User.objects.get_or_create(
        email="dev@mentora.local", defaults={"display_name": "Mentora Dev", "password": "!"},
    )
    for model_name in ("LearningPlan", "LearningHistoryEvent", "MistakeArchive"):
        apps.get_model("learning", model_name).objects.filter(owner__isnull=True).update(owner=user)


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_mistake_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mistakearchive',
            name='learning_mistake_archive_uc',
        ),
        migrations.AddField(
            model_name='learninghistoryevent',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_history_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningplan',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mistakearchive',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mistake_archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='mistakearchive',
            constraint=models.UniqueConstraint(fields=('owner', 'course_id', 'item_id'), name='learning_mistake_archive_uc'),
        ),
        migrations.RunPython(backfill_owner, migrations.RunPython.noop),
    ]
