# Generated by Django 6.0.6 on 2026-06-24 01:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_session_id', models.UUIDField(db_index=True, help_text='关联课程会话 ID')),
                ('topic_id', models.UUIDField(blank=True, help_text='关联 knowledge topic ID', null=True)),
                ('question_type', models.CharField(choices=[('single_choice', '单选题'), ('multi_choice', '多选题'), ('short_answer', '简答题')], max_length=16)),
                ('difficulty', models.IntegerField(default=3, help_text='难度等级 1-5')),
                ('question_text', models.TextField(help_text='题干')),
                ('options_json', models.JSONField(blank=True, help_text='选项列表 [{label, text}, ...]，简答题可为空', null=True)),
                ('correct_answer', models.TextField(help_text='正确答案')),
                ('explanation', models.TextField(blank=True, default='', help_text='答案解析')),
                ('source_evidence_ids', models.JSONField(default=list, help_text='题目来源证据 ID 列表（从哪些资料生成）')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('retired', '已停用')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'assessment_item',
                'indexes': [models.Index(fields=['course_session_id', 'status'], name='assessment__course__1c1db1_idx'), models.Index(fields=['topic_id'], name='assessment__topic_i_48b392_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_session_id', models.UUIDField(db_index=True)),
                ('unit_id', models.UUIDField(blank=True, help_text='关联 learning_plan_unit ID', null=True)),
                ('status', models.CharField(choices=[('created', '已创建'), ('in_progress', '进行中'), ('completed', '已完成')], default='created', max_length=16)),
                ('total_items', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('score_pct', models.IntegerField(default=0, help_text='得分百分比 0-100')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '测验会话',
                'verbose_name_plural': '测验会话',
                'db_table': 'assessment_session',
                'indexes': [models.Index(fields=['course_session_id', '-created_at'], name='assessment__course__6ff0ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=0, help_text='试卷中序号 0-based')),
                ('user_answer', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0, help_text='得分 0-1')),
                ('duration_seconds', models.IntegerField(blank=True, help_text='作答耗时（秒）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment.assessmentitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment.assessmentsession')),
            ],
            options={
                'verbose_name': '作答记录',
                'verbose_name_plural': '作答记录',
                'db_table': 'assessment_attempt',
                'ordering': ['session', 'position'],
            },
        ),
    ]
