# Generated by Django 6.0.6 on 2026-06-26 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentItemRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_revision_id', models.UUIDField(blank=True, help_text='上一版本修订 ID', null=True)),
                ('version_number', models.IntegerField(default=1, help_text='版本号，从 1 递增')),
                ('question_text', models.TextField(help_text='题干')),
                ('options_json', models.JSONField(blank=True, help_text='选项列表', null=True)),
                ('correct_answer', models.TextField(help_text='正确答案')),
                ('explanation', models.TextField(blank=True, default='', help_text='答案解析')),
                ('source_evidence_ids', models.JSONField(default=list, help_text='题目来源证据 ID 列表')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('retired', '已停用')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '题目修订',
                'verbose_name_plural': '题目修订',
                'db_table': 'assessment_item_revision',
                'ordering': ['item', '-version_number'],
            },
        ),
        migrations.RemoveIndex(
            model_name='assessmentitem',
            name='assessment__course__1c1db1_idx',
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='current_revision_id',
            field=models.UUIDField(blank=True, help_text='当前生效的修订 ID', null=True),
        ),
        migrations.AddIndex(
            model_name='assessmentitem',
            index=models.Index(fields=['course_session_id'], name='assessment__course__db0d23_idx'),
        ),
        migrations.AddField(
            model_name='assessmentitemrevision',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='assessment.assessmentitem'),
        ),
        migrations.RemoveField(
            model_name='assessmentitem',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='assessmentitem',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='assessmentitem',
            name='options_json',
        ),
        migrations.RemoveField(
            model_name='assessmentitem',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='assessmentitem',
            name='source_evidence_ids',
        ),
        migrations.RemoveField(
            model_name='assessmentitem',
            name='status',
        ),
        migrations.AddIndex(
            model_name='assessmentitemrevision',
            index=models.Index(fields=['item', '-version_number'], name='assessment__item_id_71ccf3_idx'),
        ),
    ]
