# Generated by Django 6.0.6 on 2026-06-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_add_item_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentitemrevision',
            name='validation_issues',
            field=models.JSONField(default=list, help_text='AI 自检未通过的问题列表'),
        ),
    ]
