# Generated by Django 6.0.6 on 2026-06-26 07:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_add_validation_issues'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.UUIDField(db_index=True)),
                ('issue', models.CharField(choices=[('answer_wrong', '答案错误'), ('option_overlap', '选项重叠'), ('unclear', '表述不清'), ('outdated', '内容过时'), ('other', '其他')], max_length=16)),
                ('student_note', models.TextField(blank=True, default='')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_by_revision_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '题目反馈',
                'verbose_name_plural': '题目反馈',
                'db_table': 'assessment_flagged_item',
                'indexes': [models.Index(fields=['item_id', 'resolved'], name='assessment__item_id_531508_idx')],
            },
        ),
    ]
