# Generated by Django 6.0.6 on 2026-06-26 07:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_add_flagged_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProvenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('official', '官方题库'), ('user', '用户创建'), ('ai', 'AI 生成')], max_length=16)),
                ('created_by', models.CharField(blank=True, default='', help_text='创建者标识', max_length=128)),
                ('model_request_id', models.CharField(blank=True, default='', help_text='AI 生成时关联 ModelRequest', max_length=64)),
                ('import_batch', models.CharField(blank=True, default='', help_text='批量导入批次', max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='assessment.assessmentitem')),
            ],
        ),
    ]
