# Generated by Django 5.2.15 on 2026-07-10 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owner(apps, schema_editor):
    User = apps.get_model("users", "User")
    user, _ = User.objects.get_or_create(
        email="dev@mentora.local", defaults={"display_name": "Mentora Dev", "password": "!"},
    )
    apps.get_model("assessment", "AssessmentItem").objects.filter(owner__isnull=True).update(owner=user)
    apps.get_model("assessment", "AssessmentSession").objects.filter(owner__isnull=True).update(owner=user)


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_quizgenerationjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quizgenerationjob',
            new_name='assessment__generat_8298e6_idx',
            old_name='assessment_g_cache_k_7f0a0d_idx',
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_owner, migrations.RunPython.noop),
    ]
