# Generated by Django 5.2.15 on 2026-07-10 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owner(apps, schema_editor):
    User = apps.get_model("users", "User")
    user, _ = User.objects.get_or_create(
        email="dev@mentora.local", defaults={"display_name": "Mentora Dev", "password": "!"},
    )
    apps.get_model("assessment", "QuizGenerationJob").objects.filter(
        owner__isnull=True,
    ).update(owner=user)


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_rename_assessment_g_cache_k_7f0a0d_idx_assessment__generat_8298e6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgenerationjob',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz_generation_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_owner, migrations.RunPython.noop),
    ]
