# Generated by Django 6.0.6 on 2026-06-16 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chunkprojection',
            new_name='retrieval_c_source__161748_idx',
            old_name='chunk_srcver_idx',
        ),
        migrations.RenameIndex(
            model_name='evidenceunit',
            new_name='retrieval_e_source__d58486_idx',
            old_name='evidence_srcver_page_idx',
        ),
        migrations.RenameIndex(
            model_name='sentenceprojection',
            new_name='retrieval_s_evidenc_91ee2e_idx',
            old_name='sentence_evidence_idx',
        ),
    ]
