# Generated by Django 6.0.6 on 2026-06-23 01:39

import django.contrib.postgres.search
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0004_change_embedding_dimensions_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkprojection',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, help_text='文本块向量，全量生成。', null=True),
        ),
        migrations.AlterField(
            model_name='pagetextprojection',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(help_text='PG 全文检索向量，在 save() 时由 full_text 自动同步。', null=True),
        ),
        migrations.CreateModel(
            name='EvidenceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_ids', models.JSONField(default=list, help_text='冻结的证据 ID 列表（有序）。')),
                ('scope_revision_id', models.CharField(db_index=True, help_text='课程知识作用域修订 ID，关联 CourseProfileRevision。', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '证据快照',
                'verbose_name_plural': '证据快照',
                'db_table': 'retrieval_evidence_snapshot',
                'indexes': [models.Index(fields=['scope_revision_id', '-created_at'], name='retrieval_e_scope_r_f894de_idx')],
            },
        ),
    ]
