# Generated by Django 6.0.6 on 2026-06-23 02:32

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0005_add_evidence_snapshot'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sentenceprojection',
            index=pgvector.django.indexes.IvfflatIndex(fields=['embedding'], lists=50, name='sentence_embedding_ivfflat_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
