# Generated by Django 6.0.6 on 2026-06-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0007_add_benchmark_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceunit',
            name='artifact_ref',
            field=models.CharField(blank=True, default='', help_text='对象存储引用，图片类型指向 MinIO 中的图片文件。', max_length=512),
        ),
    ]
