# Generated by Django 6.0.6 on 2026-06-30 16:41

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0008_add_evidence_artifact_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkprojection',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=2000, help_text='文本块向量，全量生成。', null=True),
        ),
        migrations.AlterField(
            model_name='sentenceprojection',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=2000, help_text='句子向量，按需求生成（不默认全量）。', null=True),
        ),
    ]
