# Generated by Django 6.0.6 on 2026-06-30 01:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_type', models.CharField(help_text='chat / pipeline / course_creation', max_length=32)),
                ('status', models.CharField(default='pending', help_text='pending / running / completed / failed / cancelled', max_length=16)),
                ('current_step_index', models.IntegerField(default=0, help_text='Pipeline 当前步骤索引')),
                ('input_json', models.JSONField(default=dict, help_text='输入快照')),
                ('output_json', models.JSONField(blank=True, help_text='输出快照', null=True)),
                ('checkpoint_data', models.JSONField(blank=True, help_text='检查点数据（崩溃恢复用）', null=True)),
                ('owner_id', models.CharField(blank=True, default='', help_text='发起用户 ID', max_length=64)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflow_runtime_state',
                'indexes': [models.Index(fields=['owner_id', 'status'], name='wrs_owner_status_idx'), models.Index(fields=['status', 'created_at'], name='wrs_status_created_idx'), models.Index(fields=['workflow_type', 'created_at'], name='wrs_type_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_id', models.CharField(help_text='持有租约的 worker 标识', max_length=64)),
                ('lease_expires_at', models.DateTimeField(help_text='租约过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='workflow_runtime.workflowstate')),
            ],
            options={
                'db_table': 'workflow_runtime_lease',
                'indexes': [models.Index(fields=['lease_expires_at'], name='wrl_expires_idx'), models.Index(fields=['worker_id'], name='wrl_worker_idx')],
            },
        ),
    ]
