# Generated by Django 5.2.15 on 2026-07-10 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owner(apps, schema_editor):
    User = apps.get_model("users", "User")
    WorkflowState = apps.get_model("workflow_runtime", "WorkflowState")
    user, _ = User.objects.get_or_create(
        email="dev@mentora.local", defaults={"display_name": "Mentora Dev", "password": "!"},
    )
    WorkflowState.objects.filter(owner__isnull=True).update(owner=user)


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_runtime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workflowstate',
            name='wrs_owner_status_idx',
        ),
        migrations.RenameField(
            model_name='workflowstate',
            old_name='owner_id',
            new_name='legacy_owner_id',
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workflowstate',
            index=models.Index(fields=['owner', 'status'], name='wrs_owner_status_idx'),
        ),
        migrations.RunPython(backfill_owner, migrations.RunPython.noop),
    ]
