# Generated by Django 5.2.15 on 2026-06-18 08:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCreationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('collecting', '收集基础信息中'), ('inquiring', 'AI 追问中'), ('generating_plan', '生成方案中'), ('completed', '已完成')], default='collecting', max_length=32)),
                ('goal', models.TextField(blank=True, default='')),
                ('level', models.CharField(blank=True, default='', max_length=64)),
                ('pace', models.CharField(blank=True, default='', max_length=64)),
                ('inquiry_history', models.JSONField(default=list)),
                ('extra', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '建课会话',
                'verbose_name_plural': '建课会话',
                'db_table': 'courses_session',
                'indexes': [models.Index(fields=['status', 'created_at'], name='courses_ses_status_a176f3_idx')],
            },
        ),
    ]
