# Generated by Django 5.2.15 on 2026-06-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreationsession',
            name='school',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
