# Generated by Django 6.0.6 on 2026-06-24 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_profile_revision_id', models.UUIDField(blank=True, help_text='当前生效的 CourseProfileRevision ID', null=True)),
                ('active_scope_revision_id', models.UUIDField(blank=True, help_text='当前生效的 CourseKnowledgeScopeRevision ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(help_text='来源建课会话', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.coursecreationsession')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'courses_course',
            },
        ),
        migrations.CreateModel(
            name='CourseKnowledgeScopeRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', help_text='版本标签，如 v1', max_length=64)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '生效中'), ('superseded', '已替代')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_revisions', to='courses.course')),
            ],
            options={
                'verbose_name': '作用域修订',
                'verbose_name_plural': '作用域修订',
                'db_table': 'courses_scope_revision',
            },
        ),
        migrations.CreateModel(
            name='CourseProfileRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_revision_id', models.UUIDField(blank=True, help_text='上一版本修订 ID', null=True)),
                ('goal', models.TextField(blank=True, default='')),
                ('level', models.CharField(blank=True, default='', max_length=64)),
                ('pace', models.CharField(blank=True, default='', max_length=64)),
                ('school', models.CharField(blank=True, default='', max_length=128)),
                ('topics_json', models.JSONField(default=dict, help_text='PlannerAgent 输出的主题树')),
                ('plan_revision_id', models.UUIDField(blank=True, help_text='关联 LearningPlanRevision ID', null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('active', '生效中'), ('superseded', '已替代')], default='draft', max_length=16)),
                ('lock_version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_revisions', to='courses.course')),
            ],
            options={
                'verbose_name': '画像修订',
                'verbose_name_plural': '画像修订',
                'db_table': 'courses_profile_revision',
            },
        ),
        migrations.CreateModel(
            name='CourseScopeBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_version_id', models.CharField(help_text='资料版本 ID', max_length=128)),
                ('role', models.CharField(choices=[('primary', '主资料'), ('reference', '参考资料'), ('exam_scope', '考试范围'), ('exercise', '练习')], default='primary', max_length=16)),
                ('position', models.IntegerField(default=0)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='courses.courseknowledgescoperevision')),
            ],
            options={
                'verbose_name': '作用域绑定',
                'verbose_name_plural': '作用域绑定',
                'db_table': 'courses_scope_binding',
                'ordering': ['revision', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='courseknowledgescoperevision',
            index=models.Index(fields=['course', '-created_at'], name='courses_sco_course__5b8501_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprofilerevision',
            index=models.Index(fields=['course', '-created_at'], name='courses_pro_course__c79330_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprofilerevision',
            index=models.Index(fields=['status'], name='courses_pro_status_b2f7b1_idx'),
        ),
    ]
