# Generated by Django 5.2.15 on 2026-06-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreationsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='coursecreationsession',
            name='status',
            field=models.CharField(choices=[('collecting', '收集基础信息中'), ('inquiring', 'AI 追问中'), ('generating_plan', '生成方案中'), ('completed', '方案已生成'), ('started', '已开始学习')], default='collecting', max_length=32),
        ),
    ]
