# Generated by Django 5.2.15 on 2026-06-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursecreationsession_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreationsession',
            name='time_budget',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
