# Generated by Django 6.0.6 on 2026-06-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_course_profile_scope'),
        ('courses', '0003_coursecreationsession_title_and_more'),
    ]

    operations = [
    ]
