# Generated by Django 5.2.15 on 2026-06-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursecreationsession_time_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreationsession',
            name='deadline',
            field=models.DateField(blank=True, help_text='考试或截止日期（选填）', null=True),
        ),
    ]
