# Generated by Django 5.2.15 on 2026-06-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursecreationsession_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreationsession',
            name='last_studied_at',
            field=models.DateTimeField(blank=True, help_text='最近一次进入学习的时间', null=True),
        ),
    ]
