# Generated by Django 6.0.6 on 2026-06-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_add_course_profile_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreationsession',
            name='profile_supplement',
            field=models.JSONField(default=dict),
        ),
    ]
