# Generated by Django 5.2.15 on 2026-07-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_session_archived_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecreationsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("collecting", "收集基础信息中"),
                    ("inquiring", "AI 追问中"),
                    ("generating_plan", "生成方案中"),
                    ("completed", "方案已生成"),
                    ("started", "已开始学习"),
                    ("archived", "已归档（已创建 Course）"),
                ],
                default="collecting",
                max_length=32,
            ),
        ),
    ]
