# Generated by Django 5.2.15 on 2026-07-10 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owner(apps, schema_editor):
    User = apps.get_model("users", "User")
    Course = apps.get_model("courses", "Course")
    Session = apps.get_model("courses", "CourseCreationSession")
    user, _ = User.objects.get_or_create(
        email="dev@mentora.local", defaults={"display_name": "Mentora Dev", "password": "!"},
    )
    Session.objects.filter(owner__isnull=True).update(owner=user)
    Course.objects.filter(owner__isnull=True).update(owner=user)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_coursecreationsession_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursecreationsession',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_creation_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_owner, migrations.RunPython.noop),
    ]
