# Generated by Django 5.2.15 on 2026-07-10 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owner(apps, schema_editor):
    User = apps.get_model("users", "User")
    Session = apps.get_model("agent_runtime", "CourseAgentSession")
    user, _ = User.objects.get_or_create(
        email="dev@mentora.local", defaults={"display_name": "Mentora Dev", "password": "!"},
    )
    Session.objects.filter(owner__isnull=True).update(owner=user)


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0002_course_agent_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseagentsession',
            old_name='owner_id',
            new_name='legacy_owner_id',
        ),
        migrations.AddField(
            model_name='courseagentsession',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_agent_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseagentmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent_runtime.courseagentsession'),
        ),
        migrations.RunPython(backfill_owner, migrations.RunPython.noop),
    ]
