# Generated by Django 6.0.6 on 2026-06-27 07:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.CharField(db_index=True, help_text='关联课程 ID', max_length=128)),
                ('name', models.CharField(help_text='主题名称', max_length=256)),
                ('level', models.IntegerField(default=0, help_text='层级: 0=根, 1=章, 2=节')),
                ('position', models.IntegerField(default=0, help_text='排序序号')),
                ('evidence_count', models.IntegerField(default=0, help_text='关联证据数')),
                ('estimated_minutes', models.IntegerField(default=0, help_text='预估学习时长（分钟）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='父主题，根节点为 None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='topics.topic')),
            ],
            options={
                'verbose_name': '知识主题',
                'verbose_name_plural': '知识主题',
                'db_table': 'topics_topic',
                'ordering': ['course_id', 'level', 'position'],
            },
        ),
        migrations.CreateModel(
            name='TopicEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('requires', '必须先学'), ('suggests', '建议先学')], default='requires', max_length=16)),
                ('source', models.ForeignKey(help_text='后置主题', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='topics.topic')),
                ('target', models.ForeignKey(help_text='前置主题', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='topics.topic')),
            ],
            options={
                'verbose_name': '主题前置关系',
                'verbose_name_plural': '主题前置关系',
                'db_table': 'topics_edge',
            },
        ),
        migrations.CreateModel(
            name='TopicEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_unit_id', models.CharField(db_index=True, help_text='关联的 EvidenceUnit ID（字符串引用，跨模块）', max_length=128)),
                ('relevance', models.FloatField(default=1.0, help_text='关联度 0-1')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='topics.topic')),
            ],
            options={
                'verbose_name': '主题证据关联',
                'verbose_name_plural': '主题证据关联',
                'db_table': 'topics_evidence',
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['course_id'], name='topics_topi_course__214eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['course_id', 'parent'], name='topics_topi_course__9b9c68_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicedge',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='topics_edge_source_target_unique'),
        ),
        migrations.AddConstraint(
            model_name='topicevidence',
            constraint=models.UniqueConstraint(fields=('topic', 'evidence_unit_id'), name='topics_evidence_topic_eid_unique'),
        ),
    ]
