# Generated by Django 5.2.15 on 2026-07-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_course_owner_coursecreationsession_owner"),
        ("topics", "0002_topic_course_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={
                "ordering": ["course", "level", "position"],
                "verbose_name": "知识主题",
                "verbose_name_plural": "知识主题",
            },
        ),
        migrations.RemoveIndex(
            model_name="topic",
            name="topics_topi_course__214eaf_idx",
        ),
        migrations.RemoveIndex(
            model_name="topic",
            name="topics_topi_course__9b9c68_idx",
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["course"], name="topics_topi_course__214eaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["course", "parent"], name="topics_topi_course__9b9c68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["legacy_course_key"], name="topics_topi_legacy__851639_idx"
            ),
        ),
    ]
