# Generated by Django 6.0.6 on 2026-07-01 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_gateway', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='modelattempt',
            new_name='mgw_att_succ_created_idx',
            old_name='mgw_attempt_success_created_idx',
        ),
    ]
